-- -*-mode:lua-*- vim:ft=lua
--[[
CAUTION: This file is automatically generated by Chezmoi.
{{- $colorscheme := .colortheme -}}
{{- if eq $colorscheme "gruvbox-dark" -}}
{{- $colorscheme = "gruvbox" -}}
{{- else if eq $colorscheme "dracula-pro" -}}
{{- $colorscheme = "dracula" -}}
{{- end -}}
{{- if not $colorscheme -}}
{{- $colorscheme = "astrodark" -}}
{{- end }}
]]

---@type LazySpec
return {
  "AstroNvim/astroui",
  ---@type AstroUIOpts
  opts = {
    -- change colorscheme
    colorscheme = "everforest",
    highlights = {
      init = {
        Normal = { bg = "NONE" },
        NormalNC = { bg = "NONE" },
        CursorLine = { bg = "#2E3440" },
        Visual = { bg = "#3B4252" },
      },
    },
    icons = {
      ActiveLSP = "",
      ActiveTS = " ",
      BufferClose = "",
      DapBreakpoint = "",
      DapBreakpointCondition = "",
      DapBreakpointRejected = "",
      DapLogPoint = "",
      DapStopped = "",
      DefaultFile = "",
      Diagnostic = "",
      DiagnosticError = "",
      DiagnosticHint = "",
      DiagnosticInfo = "",
      DiagnosticWarn = "",
      Folder = "",
      FolderEmpty = "",
      FolderOpen = "",
      Git = "",
      GitAdd = "",
      GitBranch = "",
      GitChange = "",
      GitConflict = "",
      GitDelete = "",
      GitIgnored = "",
      GitRenamed = "",
      GitStaged = "",
      GitUnstaged = "",
      GitUntracked = "",
      LSPLoaded = "",
      LSPLoading1 = "",
      LSPLoading2 = "",
      LSPLoading3 = "",
    },
  },
}
